{{- if .Values.ingress.createGcpManagedCertificate -}}
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: gofipe-cert
spec:
  domains:
    {{- range .Values.ingress.hosts }}
    - {{ .host | quote }}
    {{- end }}
{{- end -}}
