{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "gofipe.fullname" . }}
  labels:
    {{- include "gofipe.labels" . | nindent 4 }}
spec:
  {{- if and (not .Values.autoscaling.enabled) (gt (.Values.replicaCount | int) 1) }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- else if and (.Values.autoscaling.enabled) (gt (.Values.autoscaling.minReplicas | int) 1) }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "go-fipe.selectorLabels" . | nindent 6 }}
{{- end }}
